---
apiVersion: v1
kind: Secret
metadata:
  name: formular-secrets
  namespace: formular
type: Opaque
stringData:
  # Změňte tyto hodnoty podle vaší databáze!
  DB_USER: "root"
  DB_PASSWORD: "password"
  # Nebo sestavená DATABASE_URL
  DATABASE_URL: "mysql+pymysql://root:password@mariadb-service:3306/formular_db"
